# Generated by Django 2.2.1 on 2019-05-23 11:25

from django.db import migrations, models
import memo.models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_memocoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='image',
            field=models.ImageField(default='', upload_to=memo.models.get_memo_image_path),
        ),
    ]
